baseURL = 'https://dbgate.io/'
languageCode = 'en-us'
title = 'DbGate'
disableKinds = ["taxonomy"]
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
    max = "0.120.4"

[pagination]
  disableAliases = false
  pagerSize = 50
  path = 'page'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  exclude = ["purchase"]